Auto commit for changes in svelte.config.js
Changes in svelte.config.js:\n\ndiff --git a/svelte.config.js b/svelte.config.js
index 646b929..c90b403 100644
--- a/svelte.config.js
+++ b/svelte.config.js
@@ -10,7 +10,7 @@ const config = {
 		prerender: {
 			handleHttpError: ({ path, referrer, message }) => {
 				// Ignore deliberate link to shiny 404 page
-				if (path === '/not-found' && referrer === '/tools/error') {
+				if (path === '/404' && referrer === '/tools/error') {
 					return;
 				}

Signed-off-by: Memet Zx <zxce3@gnuweeb.org>